// import { Geist, Geist_Mono } from "next/font/google";
// import "../styles/globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
"use client"; // Required for Zustand

import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import { useEffect } from "react";
import useThemeStore, { loadTheme } from "@/store/themeStore"; // Import Zustand store and loadTheme

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  const { darkMode, initializeTheme } = useThemeStore();

  // Apply theme before rendering
  useEffect(() => {
    loadTheme(); // Apply dark/light theme immediately
    initializeTheme(); // Sync Zustand state
  }, []);

  return (
    <html lang="en" className={darkMode ? "dark" : ""}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased transition-all duration-300 ${
          darkMode ? "bg-gray-900 text-white" : "bg-white text-black"
        }`}
      >
        {children}
      </body>
    </html>
  );
}